name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'VERSION' # This file contains the semantic version
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'VERSION'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Read the version
      id: version
      run: echo ::set-output name=VERSION::$(cat VERSION)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rahasya:${{ steps.version.outputs.VERSION }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push the Docker image with semantic version
      run: docker push rahasya:${{ steps.version.outputs.VERSION }}
    - name: Tag the image as latest
      run: |
        docker tag rahasya:${{ steps.version.outputs.VERSION }} rahasya:latest
        docker push rahasya:latest
