name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile' # This ensures it only triggers for changes to the main Dockerfile
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile' # And for pull requests that change the main Dockerfile

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rahasya:$(date +%s)
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push the Docker image
      run: docker push rahasya:$(date +%s)
